// packages/ag-ui/src/angular/lib/approval-card.component.ts
import { ChangeDetectionStrategy, Component, computed, input, signal } from "@angular/core"
import {
  type ApprovalDecision,
  type ApprovalView,
  approvalErrorLine,
  approvalPayload,
  dispatchDecision,
  scopeLine,
} from "@b4run/ag-ui/view"

/**
 * The approval card (spec §3.2): one per pending interrupt, after the turn's
 * activity. "{agent} wants to {label}", the reason, the payload, Allow once /
 * Always allow / Deny on one row, and the scope line. `onDecide` runs on the
 * click; when it throws or rejects, the card says so and offers the buttons
 * again.
 */
@Component({
  selector: "b4-approval-card",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `<section class="b4-approval" [attr.data-state]="state()" role="alert" [attr.aria-busy]="busy() ? 'true' : null"><h3 class="b4-approval__title">{{ agent() }} wants to {{ label() }}</h3>@if (approval().message) {<p class="b4-approval__reason">{{ approval().message }}</p>}<pre class="b4-approval__payload">{{ payload() }}</pre><div class="b4-approval__actions"><button type="button" class="b4-approval__button b4-approval__button--primary" [disabled]="busy()" (click)="decide('once')">Allow once</button>@if (approval().offersAlways) {<button type="button" class="b4-approval__button b4-approval__button--secondary" [disabled]="busy()" (click)="decide('always')">Always allow</button>}<button type="button" class="b4-approval__button b4-approval__button--text" [disabled]="busy()" (click)="decide('deny')">Deny</button></div>@if (error() !== undefined) {<p class="b4-approval__error">{{ errorLine() }}</p>}@if (approval().offersAlways) {<p class="b4-approval__scope">{{ scope() }}</p>}</section>`,
})
export class ApprovalCardComponent {
  readonly approval = input.required<ApprovalView>()
  /** "The agent" for the root run, the subagent's name otherwise. */
  readonly agent = input.required<string>()
  /** The gated step's running label, lower-cased by the caller: "run a command". */
  readonly label = input.required<string>()
  readonly onDecide = input.required<(decision: ApprovalDecision) => Promise<void> | void>()

  protected readonly state = signal<"awaiting" | "deciding" | "failed">("awaiting")
  protected readonly error = signal<string | undefined>(undefined)
  protected readonly busy = computed(() => this.state() === "deciding")
  protected readonly payload = computed(() => approvalPayload(this.approval().detail))
  protected readonly scope = computed(() => scopeLine(this.approval().kind, this.approval().detail))
  protected readonly errorLine = computed(() => approvalErrorLine(this.error() ?? ""))

  protected decide(decision: ApprovalDecision): void {
    this.state.set("deciding")
    this.error.set(undefined)
    dispatchDecision(
      () => this.onDecide()(decision),
      (message) => {
        this.state.set("failed")
        this.error.set(message)
      },
    )
  }
}

// packages/ag-ui/src/react/activity/ApprovalCard.tsx
import { type ReactElement, useState } from "react"
import {
  type ApprovalDecision,
  approvalErrorLine,
  approvalPayload,
  dispatchDecision,
  scopeLine,
} from "../../view/activity-approval.js"
import type { ApprovalView } from "../../view/turns.js"

export type { ApprovalDecision }

export interface ApprovalCardProps {
  readonly approval: ApprovalView
  /** "The agent" for the root run, the subagent's name otherwise (spec §3.2). */
  readonly agent: string
  /** The gated step's running label, lower-cased by the caller: "run a command". */
  readonly label: string
  readonly onDecide: (decision: ApprovalDecision) => Promise<void> | void
}

/** The approval card (spec §3.2): one per pending interrupt, after the turn's activity. */
export function ApprovalCard({
  approval,
  agent,
  label,
  onDecide,
}: ApprovalCardProps): ReactElement {
  const [state, setState] = useState<"awaiting" | "deciding" | "failed">("awaiting")
  const [error, setError] = useState<string | undefined>(undefined)
  const decide = (decision: ApprovalDecision) => {
    setState("deciding")
    setError(undefined)
    // Dispatched on the click itself; a synchronous throw and a rejected
    // promise both land in the error callback.
    dispatchDecision(
      () => onDecide(decision),
      (message) => {
        setState("failed")
        setError(message)
      },
    )
  }
  const busy = state === "deciding"
  return (
    <section
      className="b4-approval"
      data-state={state}
      role="alert"
      {...(busy ? { "aria-busy": true } : {})}
    >
      <h3 className="b4-approval__title">
        {agent} wants to {label}
      </h3>
      {approval.message ? <p className="b4-approval__reason">{approval.message}</p> : null}
      <pre className="b4-approval__payload">{approvalPayload(approval.detail)}</pre>
      <div className="b4-approval__actions">
        <button
          type="button"
          className="b4-approval__button b4-approval__button--primary"
          disabled={busy}
          onClick={() => decide("once")}
        >
          Allow once
        </button>
        {approval.offersAlways ? (
          <button
            type="button"
            className="b4-approval__button b4-approval__button--secondary"
            disabled={busy}
            onClick={() => decide("always")}
          >
            Always allow
          </button>
        ) : null}
        <button
          type="button"
          className="b4-approval__button b4-approval__button--text"
          disabled={busy}
          onClick={() => decide("deny")}
        >
          Deny
        </button>
      </div>
      {error !== undefined ? (
        <p className="b4-approval__error">{approvalErrorLine(error)}</p>
      ) : null}
      {approval.offersAlways ? (
        <p className="b4-approval__scope">{scopeLine(approval.kind, approval.detail)}</p>
      ) : null}
    </section>
  )
}
