// packages/ag-ui-angular/src/lib/step.component.ts
import { NgComponentOutlet } from "@angular/common"
import { ChangeDetectionStrategy, Component, computed, input, type Type } from "@angular/core"
import {
  CHEVRON_GLYPH,
  ownEntry,
  type StepLabelOverrides,
  stepLabel,
  stepMeta,
  type ToolStep,
} from "@b4run/ag-ui/view"
import { SourceChipsComponent } from "./source-chips.component"
import { disclosure, liveSignal } from "./state"
import { StepDetailComponent } from "./step-detail.component"
import { StepIconComponent } from "./step-icon.component"
import { CHEVRON_TEMPLATE, SvgAttrsDirective } from "./svg"

/**
 * Per-tool views that replace a step's `b4-step-detail` (spec §3.1 "Per-tool
 * views"): a component per tool name, given the step as its `step` input. The
 * sentence line stays.
 */
export type StepRenderers = Readonly<Record<string, Type<unknown>>>

export const defaultNow = (): number => Date.now()

/**
 * One tool call as a sentence; opens to its inputs and output. Attaches to the
 * contract's own `li` (`<li b4-step [step]="…">`), so the list keeps its
 * `ol > li` structure.
 */
@Component({
  selector: "li[b4-step]",
  imports: [
    NgComponentOutlet,
    SourceChipsComponent,
    StepDetailComponent,
    StepIconComponent,
    SvgAttrsDirective,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    class: "b4-step",
    "data-kind": "tool",
    "[attr.data-state]": "rowState()",
    "[attr.data-expanded]": "panel.open() ? 'true' : null",
  },
  template: `<button type="button" class="b4-step__line" [attr.aria-expanded]="panel.open()" (click)="panel.toggle()">${CHEVRON_TEMPLATE}<b4-step-icon [name]="failed() ? 'alert' : step().icon" /><span class="b4-step__text">{{ label() }}</span>@if (meta()) {<span class="b4-step__meta">{{ meta() }}</span>}</button>@if (panel.open()) {@if (custom(); as view) {<div class="b4-step__detail"><ng-container *ngComponentOutlet="view; inputs: { step: step() }" /></div>} @else {<b4-step-detail [args]="step().args" [result]="step().result" />}}@if (step().sources; as sources) {<b4-source-chips [sources]="sources" />}`,
})
export class StepComponent {
  readonly step = input.required<ToolStep>()
  readonly labels = input<StepLabelOverrides | undefined>(undefined)
  readonly renderStep = input<StepRenderers | undefined>(undefined)
  /** The clock; defaults to `Date.now`. Inject in tests. */
  readonly now = input<() => number>(defaultNow)

  protected readonly chevron = CHEVRON_GLYPH
  private readonly live = liveSignal(this.step, () => this.now()())
  protected readonly failed = computed(() => this.step().status === "failed")
  protected readonly rowState = computed(() =>
    this.step().status === "running" && !this.live() ? "pending" : this.step().status,
  )
  // Keyed by `startedAt`: the same call going awaiting → running keeps what
  // the user opened; a re-presented call hands control back to automation.
  protected readonly panel = disclosure(this.failed, this.live, () => this.step().startedAt)
  protected readonly label = computed(() => stepLabel(this.step(), this.labels()))
  protected readonly meta = computed(() => stepMeta(this.step()))
  protected readonly custom = computed(() => ownEntry(this.renderStep(), this.step().name))
}

// packages/ag-ui/src/react/activity/Step.tsx
import type { ReactElement, ReactNode } from "react"
import { ownEntry, stepMeta } from "../../view/activity-format.js"
import { type StepLabelOverrides, stepLabel } from "../../view/labels.js"
import type { ToolStep } from "../../view/turns.js"
import { Disclosure, useDisclosure } from "./Disclosure.js"
import { StepIcon } from "./icons.js"
import { SourceChips } from "./SourceChips.js"
import { StatusText } from "./StatusText.js"
import { StepDetail } from "./StepDetail.js"
import { useLive } from "./useLive.js"

/** An app view that replaces a step's `StepDetail` (spec §3.1 "Per-tool views"). */
export type StepRenderer = (props: { readonly step: ToolStep }) => ReactNode
export type StepRenderers = Readonly<Record<string, StepRenderer>>

export interface StepProps {
  readonly step: ToolStep
  readonly labels?: StepLabelOverrides | undefined
  readonly renderStep?: StepRenderers | undefined
  readonly now: () => number
}

/** One tool call as a sentence; opens to its inputs and output (spec §3 `Step`). */
export function Step({ step, labels, renderStep, now }: StepProps): ReactElement {
  const live = useLive(step, now)
  const state = step.status === "running" && !live ? "pending" : step.status
  const failed = step.status === "failed"
  // Keyed by `startedAt`: the same call going awaiting → running keeps what
  // the user opened; a re-presented call hands control back to automation.
  const { open, toggle } = useDisclosure(failed, live, step.startedAt)
  // Own-key lookup: tool names come off the wire.
  const custom = ownEntry(renderStep, step.name)
  return (
    <li
      className="b4-step"
      data-state={state}
      data-kind="tool"
      {...(open ? { "data-expanded": "true" } : {})}
    >
      <Disclosure
        className="b4-step__line"
        open={open}
        onToggle={toggle}
        summary={
          <>
            <StepIcon name={failed ? "alert" : step.icon} />
            <span className="b4-step__text">{stepLabel(step, labels)}</span>
            <StatusText>{stepMeta(step)}</StatusText>
          </>
        }
      >
        {custom ? (
          <div className="b4-step__detail">{custom({ step })}</div>
        ) : (
          <StepDetail args={step.args} result={step.result} />
        )}
      </Disclosure>
      {step.sources ? <SourceChips sources={step.sources} /> : null}
    </li>
  )
}
