// packages/ag-ui/src/angular/lib/subagent-step.component.ts
import { ChangeDetectionStrategy, Component, computed, forwardRef, input } from "@angular/core"
import {
  CHEVRON_GLYPH,
  isSubagentLive,
  type StepLabelOverrides,
  type SubagentStep,
  subagentMeta,
  subagentRowState,
  subagentSettledText,
} from "@b4run/ag-ui/view"
import { disclosure } from "./state.js"
import { defaultNow, type StepRenderers } from "./step.component.js"
import { StepIconComponent } from "./step-icon.component.js"
import { CHEVRON_TEMPLATE, SvgAttrsDirective } from "./svg.js"
// Circular with turn-activity.component.ts: both sides reference the other
// through `forwardRef`, so either may load first.
import { TurnActivityComponent } from "./turn-activity.component.js"

/**
 * "Asked researcher", its description as a muted line beneath, with the
 * child's own activity nested; folds to "researcher finished · 5 steps".
 * Descriptions are third-person summaries, so they are never spliced into the
 * sentence. A settled child that took no steps has nothing to open, so its
 * line is a plain `span`. Attaches to the contract's `li`:
 * `<li b4-subagent-step [step]="…">`.
 */
@Component({
  selector: "li[b4-subagent-step]",
  imports: [forwardRef(() => TurnActivityComponent), StepIconComponent, SvgAttrsDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    class: "b4-step",
    "data-kind": "subagent",
    "[attr.data-state]": "rowState()",
    "[attr.data-expanded]": "panel.open() && !empty() ? 'true' : null",
  },
  template: `@if (empty()) {<span class="b4-step__line b4-step__line--static"><b4-step-icon [name]="step().status === 'failed' ? 'alert' : 'agent'" /><span class="b4-step__text">{{ settledText() }}</span>@if (meta()) {<span class="b4-step__meta">{{ meta() }}</span>}</span>} @else {<button type="button" class="b4-step__line" [attr.aria-expanded]="panel.open()" (click)="panel.toggle()">${CHEVRON_TEMPLATE}<b4-step-icon [name]="step().status === 'failed' ? 'alert' : 'agent'" /><span class="b4-step__text">@if (live()) {Asked <b>{{ step().name }}</b>@if (step().description) {<span class="b4-step__note">{{ step().description }}</span>}} @else {<ng-container>{{ settledText() }}</ng-container>}</span>@if (meta()) {<span class="b4-step__meta">{{ meta() }}</span>}</button>@if (panel.open()) {<div class="b4-step__children"><b4-turn-activity [turn]="step().turn" [labels]="labels()" [renderStep]="renderStep()" [now]="now()" [nested]="{ name: step().name, status: step().status }" /></div>}}`,
})
export class SubagentStepComponent {
  readonly step = input.required<SubagentStep>()
  readonly labels = input<StepLabelOverrides | undefined>(undefined)
  readonly renderStep = input<StepRenderers | undefined>(undefined)
  readonly now = input<() => number>(defaultNow)

  protected readonly chevron = CHEVRON_GLYPH
  protected readonly live = computed(() => isSubagentLive(this.step()))
  protected readonly rowState = computed(() => subagentRowState(this.step().status))
  protected readonly settledText = computed(() => subagentSettledText(this.step()))
  protected readonly meta = computed(() => subagentMeta(this.step()))
  /** A settled child that took no steps has nothing to open: its line is a plain `span`. */
  protected readonly empty = computed(() => !this.live() && this.step().turn.steps.length === 0)
  protected readonly panel = disclosure(
    () => !this.empty() && (this.live() || this.step().status === "failed"),
    this.live,
    () => this.step().startedAt,
  )
}

// packages/ag-ui/src/react/activity/SubagentStep.tsx
import type { ReactElement } from "react"
import {
  isSubagentLive,
  subagentMeta,
  subagentRowState,
  subagentSettledText,
} from "../../view/activity-format.js"
import type { StepLabelOverrides } from "../../view/labels.js"
import type { SubagentStep as SubagentStepView } from "../../view/turns.js"
import { Disclosure, useDisclosure } from "./Disclosure.js"
import { StepIcon } from "./icons.js"
import { StatusText } from "./StatusText.js"
import type { StepRenderers } from "./Step.js"
// Circular with TurnActivity.tsx: each references the other only while
// rendering, never at module top level, so the ESM cycle resolves either way.
import { TurnActivity } from "./TurnActivity.js"

export interface SubagentStepProps {
  readonly step: SubagentStepView
  readonly labels?: StepLabelOverrides | undefined
  readonly renderStep?: StepRenderers | undefined
  readonly now: () => number
}

/**
 * "Asked researcher", its description as a muted line beneath, with the
 * child's own activity nested (spec §3 `SubagentStep`). Descriptions are
 * third-person summaries ("Briefs the weather …"), so they are never spliced
 * into the sentence. A settled child that took no steps has nothing to open,
 * so its line is a plain `span` rather than a button.
 */
export function SubagentStep({ step, labels, renderStep, now }: SubagentStepProps): ReactElement {
  const live = isSubagentLive(step)
  const empty = !live && step.turn.steps.length === 0
  const autoOpen = !empty && (live || step.status === "failed")
  const { open, toggle } = useDisclosure(autoOpen, live, step.startedAt)
  const text = live ? (
    <>
      Asked <b>{step.name}</b>
      {step.description ? <span className="b4-step__note">{step.description}</span> : null}
    </>
  ) : (
    subagentSettledText(step)
  )
  const summary = (
    <>
      <StepIcon name={step.status === "failed" ? "alert" : "agent"} />
      <span className="b4-step__text">{text}</span>
      <StatusText>{subagentMeta(step)}</StatusText>
    </>
  )
  if (empty) {
    return (
      <li className="b4-step" data-state={subagentRowState(step.status)} data-kind="subagent">
        <span className="b4-step__line b4-step__line--static">{summary}</span>
      </li>
    )
  }
  return (
    <li
      className="b4-step"
      data-state={subagentRowState(step.status)}
      data-kind="subagent"
      {...(open ? { "data-expanded": "true" } : {})}
    >
      <Disclosure
        className="b4-step__line"
        open={open}
        onToggle={toggle}
        panelClassName="b4-step__children"
        summary={summary}
      >
        <TurnActivity
          turn={step.turn}
          labels={labels}
          renderStep={renderStep}
          now={now}
          nested={{ name: step.name, status: step.status }}
        />
      </Disclosure>
    </li>
  )
}
