// packages/ag-ui-angular/src/lib/turn-activity.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from "@angular/core"
import {
  CHEVRON_GLYPH,
  type GroupedStep,
  groupSteps,
  type NestedTurn,
  nestedSummaryLine,
  type StepLabelOverrides,
  summaryLine,
  type TurnView,
} from "@b4run/ag-ui/view"
import { PlanStepComponent } from "./plan-step.component"
import { ReasoningStepComponent } from "./reasoning-step.component"
import { disclosure, elapsedSignal } from "./state"
import { defaultNow, StepComponent, type StepRenderers } from "./step.component"
import { StepGroupComponent } from "./step-group.component"
import { SubagentStepComponent } from "./subagent-step.component"
import { CHEVRON_TEMPLATE, SvgAttrsDirective } from "./svg"

const trackItem = (item: GroupedStep): string =>
  item.kind === "group" ? `g:${item.steps[0]?.id}` : item.id

/**
 * The summary line plus the step list for one turn (or one subagent run,
 * nested): working, awaiting, done, failed or stopped. Give it a `TurnView`
 * from `reduceTurns` (`@b4run/ag-ui/view`) and it renders the turn. Open while
 * live, folded once settled; a turn settled when it first renders ("restored")
 * starts folded.
 */
@Component({
  selector: "b4-turn-activity",
  imports: [
    PlanStepComponent,
    ReasoningStepComponent,
    StepComponent,
    StepGroupComponent,
    SubagentStepComponent,
    SvgAttrsDirective,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  // One live region per turn (spec §5.5). It carries the sentence only, never
  // the ticking time, so its text node changes only when the sentence does.
  template: `<section class="b4-turn" [attr.data-state]="turn().status" [attr.data-expanded]="panel.open() ? 'true' : null"><button type="button" class="b4-turn__summary" [attr.aria-expanded]="panel.open()" (click)="panel.toggle()">${CHEVRON_TEMPLATE}<span class="b4-turn__text" [attr.data-live]="line().live ? 'true' : null">{{ line().text }}</span>@if (line().meta) {<span class="b4-turn__time">{{ line().meta }}</span>}</button>@if (panel.open()) {<ol class="b4-turn__steps">@for (item of grouped(); track trackItem(item)) {@switch (item.kind) {@case ("group") {<li b4-step-group [group]="item" [labels]="labels()" [renderStep]="renderStep()" [now]="now()"></li>}@case ("tool") {<li b4-step [step]="item" [labels]="labels()" [renderStep]="renderStep()" [now]="now()"></li>}@case ("plan") {<li b4-plan-step [step]="item" [live]="turn().status === 'working'"></li>}@case ("reasoning") {<li b4-reasoning-step [step]="item"></li>}@case ("subagent") {<li b4-subagent-step [step]="item" [labels]="labels()" [renderStep]="renderStep()" [now]="now()"></li>}}}</ol>}<span class="b4-visually-hidden" role="status">{{ line().text }}</span></section>`,
})
export class TurnActivityComponent {
  readonly turn = input.required<TurnView>()
  readonly labels = input<StepLabelOverrides | undefined>(undefined)
  readonly renderStep = input<StepRenderers | undefined>(undefined)
  /** The clock; defaults to `Date.now`. Inject in tests. */
  readonly now = input<() => number>(defaultNow)
  /** Set when this is a subagent's turn: the summary names the subagent instead. */
  readonly nested = input<NestedTurn | undefined>(undefined)

  protected readonly chevron = CHEVRON_GLYPH
  protected readonly trackItem = trackItem
  private readonly live = computed(() => {
    const status = this.turn().status
    return status === "working" || status === "awaiting"
  })
  private readonly sampled = elapsedSignal(this.live, () => this.now()())
  protected readonly line = computed(() => {
    const nested = this.nested()
    return nested
      ? nestedSummaryLine(this.turn(), nested, this.sampled(), this.labels())
      : summaryLine(this.turn(), this.sampled(), this.labels())
  })
  // No key: a turn that becomes live again is automation's.
  protected readonly panel = disclosure(this.live, this.live)
  protected readonly grouped = computed(() => groupSteps(this.turn().steps, this.labels()))
}

// packages/ag-ui/src/react/activity/TurnActivity.tsx
import { type ReactElement, useMemo } from "react"
import { type NestedTurn, nestedSummaryLine, summaryLine } from "../../view/activity-format.js"
import { groupSteps, type StepLabelOverrides } from "../../view/labels.js"
import type { TurnView } from "../../view/turns.js"
import { Disclosure, useDisclosure } from "./Disclosure.js"
import { PlanStep } from "./PlanStep.js"
import { ReasoningStep } from "./ReasoningStep.js"
import { Step, type StepRenderers } from "./Step.js"
import { StepGroup } from "./StepGroup.js"
import { SubagentStep } from "./SubagentStep.js"
import { useElapsed } from "./useLive.js"

export interface TurnActivityProps {
  readonly turn: TurnView
  readonly labels?: StepLabelOverrides | undefined
  readonly renderStep?: StepRenderers | undefined
  /** The clock; defaults to `Date.now`. Inject in tests. */
  readonly now?: (() => number) | undefined
  /** Set when this is a subagent's turn: the summary names the subagent instead. */
  readonly nested?: NestedTurn | undefined
}

const defaultNow = () => Date.now()
const isLive = (turn: TurnView) => turn.status === "working" || turn.status === "awaiting"

/** The summary line plus the step list for one turn (spec §3 `TurnActivity`). */
export function TurnActivity({
  turn,
  labels,
  renderStep,
  now = defaultNow,
  nested,
}: TurnActivityProps): ReactElement {
  const live = isLive(turn)
  const sampled = useElapsed(live, now)
  const line = nested
    ? nestedSummaryLine(turn, nested, sampled, labels)
    : summaryLine(turn, sampled, labels)
  // Open while live, folded once settled; a turn settled at mount ("restored")
  // starts folded. No key: a turn that becomes live again is automation's.
  const { open, toggle } = useDisclosure(live, live)
  const grouped = useMemo(() => groupSteps(turn.steps, labels), [turn.steps, labels])

  return (
    <section
      className="b4-turn"
      data-state={turn.status}
      {...(open ? { "data-expanded": "true" } : {})}
    >
      <Disclosure
        className="b4-turn__summary"
        open={open}
        onToggle={toggle}
        summary={
          <>
            <span className="b4-turn__text" {...(line.live ? { "data-live": "true" } : {})}>
              {line.text}
            </span>
            {line.meta ? <span className="b4-turn__time">{line.meta}</span> : null}
          </>
        }
      >
        <ol className="b4-turn__steps">
          {grouped.map((item) => {
            switch (item.kind) {
              case "group":
                return (
                  <StepGroup
                    key={`g:${item.steps[0]?.id}`}
                    group={item}
                    labels={labels}
                    renderStep={renderStep}
                    now={now}
                  />
                )
              case "tool":
                return (
                  <Step
                    key={item.id}
                    step={item}
                    labels={labels}
                    renderStep={renderStep}
                    now={now}
                  />
                )
              case "plan":
                return <PlanStep key={item.id} step={item} live={turn.status === "working"} />
              case "reasoning":
                return <ReasoningStep key={item.id} step={item} />
              default:
                return (
                  <SubagentStep
                    key={item.id}
                    step={item}
                    labels={labels}
                    renderStep={renderStep}
                    now={now}
                  />
                )
            }
          })}
        </ol>
      </Disclosure>
      {/*
        One live region per turn (spec §5.5). It carries the sentence only, never
        the ticking time, so React touches this text node only when the sentence
        itself changes — a step starting or the turn settling — not every second.
      */}
      <span className="b4-visually-hidden" role="status">
        {line.text}
      </span>
    </section>
  )
}
