// packages/ag-ui/src/react/activity/StepGroup.tsx
import type { ReactElement } from "react"
import { groupMeta } from "../../view/activity-format.js"
import type { StepGroup as StepGroupView, StepLabelOverrides } from "../../view/labels.js"
import { Disclosure, useDisclosure } from "./Disclosure.js"
import { StepIcon } from "./icons.js"
import { StatusText } from "./StatusText.js"
import { Step, type StepRenderers } from "./Step.js"

export interface StepGroupProps {
  readonly group: StepGroupView
  readonly labels?: StepLabelOverrides | undefined
  readonly renderStep?: StepRenderers | undefined
  readonly now: () => number
}

/**
 * Consecutive done calls of one tool, merged (spec §3 `StepGroup`). The label
 * already carries the count, so the meta shows the merged sources count when
 * any; the row opens to the individual steps.
 */
export function StepGroup({ group, labels, renderStep, now }: StepGroupProps): ReactElement {
  const { open, toggle } = useDisclosure(false, false)
  return (
    <li
      className="b4-step"
      data-state="done"
      data-kind="group"
      {...(open ? { "data-expanded": "true" } : {})}
    >
      <Disclosure
        className="b4-step__line"
        open={open}
        onToggle={toggle}
        panelClassName="b4-step__children"
        summary={
          <>
            <StepIcon name={group.steps[0]?.icon} />
            <span className="b4-step__text">{group.label}</span>
            <StatusText>{groupMeta(group)}</StatusText>
          </>
        }
      >
        <ol className="b4-turn__steps">
          {group.steps.map((step) => (
            <Step key={step.id} step={step} labels={labels} renderStep={renderStep} now={now} />
          ))}
        </ol>
      </Disclosure>
    </li>
  )
}

// packages/ag-ui/src/angular/lib/step-group.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from "@angular/core"
import {
  CHEVRON_GLYPH,
  groupMeta,
  type StepGroup,
  type StepLabelOverrides,
} from "@b4run/ag-ui/view"
import { disclosure } from "./state.js"
import { defaultNow, StepComponent, type StepRenderers } from "./step.component.js"
import { StepIconComponent } from "./step-icon.component.js"
import { CHEVRON_TEMPLATE, SvgAttrsDirective } from "./svg.js"

const never = () => false

/**
 * Consecutive done calls of one tool, merged ("Searched the corpus 2 times");
 * the meta counts the merged sources, and the row opens to the individual
 * steps. Attaches to the contract's `li`: `<li b4-step-group [group]="…">`.
 */
@Component({
  selector: "li[b4-step-group]",
  imports: [StepComponent, StepIconComponent, SvgAttrsDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    class: "b4-step",
    "data-state": "done",
    "data-kind": "group",
    "[attr.data-expanded]": "panel.open() ? 'true' : null",
  },
  template: `<button type="button" class="b4-step__line" [attr.aria-expanded]="panel.open()" (click)="panel.toggle()">${CHEVRON_TEMPLATE}<b4-step-icon [name]="group().steps[0]?.icon" /><span class="b4-step__text">{{ group().label }}</span>@if (meta()) {<span class="b4-step__meta">{{ meta() }}</span>}</button>@if (panel.open()) {<div class="b4-step__children"><ol class="b4-turn__steps">@for (step of group().steps; track step.id) {<li b4-step [step]="step" [labels]="labels()" [renderStep]="renderStep()" [now]="now()"></li>}</ol></div>}`,
})
export class StepGroupComponent {
  readonly group = input.required<StepGroup>()
  readonly labels = input<StepLabelOverrides | undefined>(undefined)
  readonly renderStep = input<StepRenderers | undefined>(undefined)
  readonly now = input<() => number>(defaultNow)

  protected readonly chevron = CHEVRON_GLYPH
  protected readonly panel = disclosure(never, never)
  protected readonly meta = computed(() => groupMeta(this.group()))
}
